version: "3.8"

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: next
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/next
      BACKEND_URL: http://web:3000
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run dev"

volumes:
  db_data:
